export enum QuizCategory {
  GENERAL_KNOWLEDGE = 'GENERAL_KNOWLEDGE',
  SCIENCE_AND_NATURE = 'SCIENCE_AND_NATURE',
  HISTORY = 'HISTORY',
  GEOGRAPHY = 'GEOGRAPHY',
  SPORTS = 'SPORTS',
  ENTERTAINMENT = 'ENTERTAINMENT',
  ART_AND_LITERATURE = 'ART_AND_LITERATURE',
  TECHNOLOGY = 'TECHNOLOGY',
  MATHEMATICS = 'MATHEMATICS',
  POP_CULTURE = 'POP_CULTURE',
}
