FROM node:22-alpine

LABEL maintainer="l.nowosielski.680@studms.ug.edu.pl"

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 4200

CMD ["pnpm","start", "--host", "0.0.0.0"]
