FROM node:22-alpine

LABEL maintainer="l.nowosielski.680@studms.ug.edu.pl"

WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npm install -g @angular/cli@latest

COPY . .

EXPOSE 4200

CMD ["ng","serve","--host","0.0.0.0"]
