import { Page } from '@/app/core/types/page';
import { LeaderboardEntry } from '@/app/features/leaderboards/types/leaderboard-entry';

export const MOCK_LEADERBOARD_PAGE: Page<LeaderboardEntry> = {
  content: [
    {
      id: '1',
      username: 'QuizMaster',
      score: 9850,
      rank: 1,
      wins: 145,
      winRate: 87.3,
    },
    {
      id: '2',
      username: 'Brainiac',
      score: 9720,
      rank: 2,
      wins: 142,
      winRate: 85.5,
    },
    {
      id: '3',
      username: 'Trivia_Pro',
      score: 9650,
      rank: 3,
      wins: 138,
      winRate: 83.1,
    },
    {
      id: '4',
      username: 'KnowledgeKing',
      score: 9520,
      rank: 4,
      wins: 135,
      winRate: 81.8,
    },
    {
      id: '5',
      username: 'MindGames',
      score: 9380,
      rank: 5,
      wins: 130,
      winRate: 78.9,
    },
    {
      id: '6',
      username: 'SmartyPants',
      score: 9150,
      rank: 6,
      wins: 125,
      winRate: 75.6,
    },
    {
      id: '7',
      username: 'QuizGenius',
      score: 8920,
      rank: 7,
      wins: 118,
      winRate: 72.3,
    },
    {
      id: '8',
      username: 'FactFinder',
      score: 8780,
      rank: 8,
      wins: 112,
      winRate: 68.9,
    },
    {
      id: '9',
      username: 'CerebrumChamp',
      score: 8620,
      rank: 9,
      wins: 108,
      winRate: 65.5,
    },
    {
      id: '10',
      username: 'WizardOfWisdom',
      score: 8450,
      rank: 10,
      wins: 102,
      winRate: 61.8,
    },
  ],
  pageable: {
    pageNumber: 0,
    pageSize: 10,
    sort: {
      unsorted: false,
      sorted: true,
      empty: false,
    },
    offset: 0,
    unpaged: false,
    paged: true,
  },
  totalPages: 5,
  totalElements: 47,
  last: false,
  numberOfElements: 10,
  first: true,
  size: 10,
  number: 0,
  sort: {
    unsorted: false,
    sorted: true,
    empty: false,
  },
  empty: false,
};
